resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
<<<<<<< HEAD
  newName: tfgco/kubernetes-crossplane-infrastructure-operator
  newTag: v0.7.0-alpha
=======
  newName: tfgco/provider-crossplane
  newTag: v0.8.0-rc2
>>>>>>> 6d6c2be (chore: create detachSGFromInstances and update manifests)
