---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: KopsMachinePool
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: test-cluster-a.<DOMAIN>
  name: nodes-extra
  namespace: k8s-test-cluster-a
spec:
  clusterName: test-cluster-a.<DOMAIN>
  kopsInstanceGroupSpec:
    associatePublicIP: false
    cloudLabels:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster/test-cluster-a.<DOMAIN>: "true"
    image: ubuntu/ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20230325
    machineType: c5.2xlarge
    maxSize: 5
    minSize: 1
    nodeLabels:
      kops.k8s.io/cluster: test-cluster-a.<DOMAIN>
      kops.k8s.io/cluster-name: test-cluster-a.<DOMAIN>
      kops.k8s.io/instance-group-name: nodes-extra
      kops.k8s.io/instance-group-role: Node
      kops.k8s.io/instancegroup: nodes-extra
      kops.k8s.io/managed-by: kops-controller
      nodes: "true"
    role: Node
    rootVolume: 
      size: 60
      type: gp3
    subnets:
    - default
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: test-cluster-a.<DOMAIN>
  name: nodes-extra
  namespace: k8s-test-cluster-a
spec:
  clusterName: test-cluster-a.<DOMAIN>
  minReadySeconds: 0
  replicas: 1
  template:
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: test-cluster-a.<DOMAIN>
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
        kind: KopsMachinePool
        name: nodes-extra
        namespace: k8s-test-cluster-a
---
apiVersion: ec2.aws.wildlife.io/v1alpha2
kind: SecurityGroup
metadata:
  name: test-sg-cluster-a-nodes-extra
spec:
  infrastructureRef:
  - apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: KopsMachinePool
    name: nodes-extra
    namespace: k8s-test-cluster-a
  ingressRules:
  - allowedCIDRs:
    - 10.0.0.0/16
    ipProtocol: "-1"