# permissions for end users to edit clustermeshes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: clustermesh-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: migration-kubernetes-crossplane-infrastructure-operator
    app.kubernetes.io/part-of: migration-kubernetes-crossplane-infrastructure-operator
    app.kubernetes.io/managed-by: kustomize
  name: clustermesh-editor-role
rules:
- apiGroups:
  - clustermesh.infrastructure.wildlife.io
  resources:
  - clustermeshes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - clustermesh.infrastructure.wildlife.io
  resources:
  - clustermeshes/status
  verbs:
  - get
