---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - clustermesh.infrastructure.wildlife.io
  resources:
  - clustermeshes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - clustermesh.infrastructure.wildlife.io
  resources:
  - clustermeshes/finalizers
  verbs:
  - update
- apiGroups:
  - clustermesh.infrastructure.wildlife.io
  resources:
  - clustermeshes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - controlplane.cluster.x-k8s.io
  resources:
  - kopscontrolplanes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ec2.aws.crossplane.io
  resources:
  - securitygroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - kopsmachinepools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infrastructure.wildlife.io
  resources:
  - securitygroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructure.wildlife.io
  resources:
  - securitygroups/finalizers
  verbs:
  - update
- apiGroups:
  - infrastructure.wildlife.io
  resources:
  - securitygroups/status
  verbs:
  - get
  - patch
  - update
