@startuml clustermesh-controller
start
:Get Cluster CR;
if (Is clustermesh enabled for that Cluster?) is (true) then
    if (Clustermesh CR exists?) is (true) then
        if (Is Cluster belongs to Clustermesh already?) is (false) then
            :Add Cluster to Clustermesh CR;
        endif
        if (Are VPC peering connections established between each cluster in the Clustermesh?) is (false) then
            :Create VPC Peerings to each Cluster of the Clustermesh;
        endif
        if (Is Wildlife Security Group created for the Cluster?) is (false) then
            :Create a Wildlife Security Group for the Cluster that permits communication with other clusters in the Clustermesh;
        else 
            :Update the Wildlife Security Group of the Cluster permitting communication with other clusters in the Clustermesh;
        endif
        if (Are Routes created for each VPC Peering?) is (false) then
            :Create Routes for each VPC Peering;
        endif
        :Validate Clustermesh;
    else (false) 
        :Create Clustermesh CR with the Cluster;
    endif
else (false)
    if (Is Cluster belongs to any Clustermesh?) is (true) then
        :Delete Wildlife Security Group of the Cluster;
        :Delete VPC Peerings related to the Cluster;
        :Remove Cluster from Clustermesh;
        if (Is the cluster the only one in the Clustermesh?) is (true) then
            :Delete Clustermesh CR;
        endif
    endif
endif
stop
@enduml
